# Generated by Django 3.2.4 on 2021-06-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systemic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('body', models.TextField(null=True)),
                ('question1', models.TextField(null=True)),
                ('question2', models.TextField(null=True)),
                ('question3', models.TextField(null=True)),
            ],
        ),
    ]
